import { createActionGroup, emptyProps, props } from '@ngrx/store';
import type { ModelDto, CapabilitiesDto, ProcessingConfig, ShortcutConfig, VramResponse } from '@photofant/models';

export const modelsActions = createActionGroup({
  source: 'Models',
  events: {
    'Load Models':               emptyProps(),
    'Load Models Success':       props<{ models: ModelDto[] }>(),
    'Load Models Failure':       props<{ error: string }>(),
    'Load Capabilities':         emptyProps(),
    'Load Capabilities Success': props<{ capabilities: CapabilitiesDto }>(),
    'Load Capabilities Failure': props<{ error: string }>(),
    'Load Config':                         emptyProps(),
    'Load Config Success':                 props<{ modelsDir: string; dataRoot: string | null; processingConfig: ProcessingConfig; keyboardShortcuts: ShortcutConfig | null }>(),
    'Load Config Failure':                 props<{ error: string }>(),
    'Update Processing Config':            props<{ patch: Partial<ProcessingConfig> }>(),
    'Update Processing Config Success':    props<{ processingConfig: ProcessingConfig }>(),
    'Update Processing Config Failure':    props<{ error: string }>(),
    'Update Shortcuts':         props<{ config: ShortcutConfig | null }>(),
    'Update Shortcuts Success': props<{ config: ShortcutConfig | null }>(),
    'Update Shortcuts Failure': props<{ error: string }>(),
    'Download Model':            props<{ manifestId: string; licenseAck: boolean }>(),
    'Download Model Success':    props<{ jobId: string; manifestId: string }>(),
    'Download Model Failure':    props<{ manifestId: string; error: string }>(),
    'Register Local':            props<{ manifestId: string; path: string; components?: Record<string, string> }>(),
    'Register Local Components': props<{ manifestId: string; components: Record<string, string> }>(),
    'Register Local Success':    props<{ model: ModelDto; warnings: string[] }>(),
    'Register Local Failure':    props<{ manifestId: string; error: string; code: string }>(),
    'Clear Bind Error':          emptyProps(),
    'Load Vram':                 emptyProps(),
    'Load Vram Success':         props<{ vram: VramResponse }>(),
    'Load Vram Failure':         props<{ error: string }>(),
    'Download Job Completed':    props<{ manifestId: string }>(),
    'Download Job Failed':       props<{ manifestId: string; error: string }>(),
    'Delete Model':              props<{ manifestId: string }>(),
    'Delete Model Success':      props<{ manifestId: string }>(),
    'Delete Model Failure':      props<{ error: string }>(),
    'Update Models Dir':         props<{ path: string }>(),
    'Update Models Dir Success': props<{ modelsDir: string }>(),
    'Update Models Dir Failure': props<{ error: string }>(),
    'Update Data Root':          props<{ path: string }>(),
    'Update Data Root Success':  props<{ dataRoot: string }>(),
    'Update Data Root Failure':  props<{ error: string }>(),
  },
});
