import { knowledgeFeature } from './knowledge.reducer';

const {
  selectAll: selectDomains,
  selectDomainsLoading,
  selectDomainsError,
  selectIsSaving,
  selectSaveError,
  selectLastCreatedEntity,
  selectLastUpdatedEntity,
  selectAllTasks,
  selectTasksLoading,
  selectTasksError,
  selectAllEntities,
  selectEntityDictionary,
  selectEntitiesLoading,
  selectEntitiesError,
  selectAiAutonomy,
  selectSuggestionLoading,
  selectSuggestionResult,
  selectSuggestionError,
  selectInterviewLoading,
  selectInterviewResult,
  selectInterviewError,
} = knowledgeFeature;

export const knowledgeSelectors = {
  selectDomains,
  selectDomainsLoading,
  selectDomainsError,
  selectIsSaving,
  selectSaveError,
  selectLastCreatedEntity,
  selectLastUpdatedEntity,
  selectAllTasks,
  selectTasksLoading,
  selectTasksError,
  selectAllEntities,
  selectEntityDictionary,
  selectEntitiesLoading,
  selectEntitiesError,
  selectAiAutonomy,
  selectSuggestionLoading,
  selectSuggestionResult,
  selectSuggestionError,
  selectInterviewLoading,
  selectInterviewResult,
  selectInterviewError,
};
