import { createActionGroup, emptyProps, props } from '@ngrx/store';
import type {
  AiAutonomyDto,
  CreateEntityRequest,
  DomainDto,
  EntityDto,
  ImportSuggestionRequest,
  InterviewSynthesizeRequest,
  KnowledgeImportResult,
  KnowledgeInterviewResult,
  TaskDto,
  UpdateEntityRequest,
} from '@photofant/models';

export const knowledgeActions = createActionGroup({
  source: 'Knowledge',
  events: {
    'Load Domains':         emptyProps(),
    'Load Domains Success': props<{ domains: DomainDto[] }>(),
    'Load Domains Failure': props<{ error: string }>(),
    'Load Entities':         emptyProps(),
    'Load Entities Success': props<{ entities: EntityDto[] }>(),
    'Load Entities Failure': props<{ error: string }>(),
    'Create Entity':            props<{ request: CreateEntityRequest }>(),
    'Create Entity Success':    props<{ entity: EntityDto }>(),
    'Create Entity Failure':    props<{ error: string }>(),
    'Update Entity':            props<{ entityId: string; patch: UpdateEntityRequest }>(),
    'Update Entity Success':    props<{ entity: EntityDto }>(),
    'Update Entity Failure':    props<{ error: string }>(),
    'Reset Create Entity State': emptyProps(),
    'Load Tasks':            emptyProps(),
    'Load Tasks Success':    props<{ tasks: TaskDto[] }>(),
    'Load Tasks Failure':    props<{ error: string }>(),
    'Resolve Task':          props<{ taskId: number }>(),
    'Resolve Task Success':  props<{ task: TaskDto }>(),
    'Resolve Task Failure':  props<{ error: string }>(),
    'Dismiss Task':          props<{ taskId: number }>(),
    'Dismiss Task Success':  props<{ task: TaskDto }>(),
    'Dismiss Task Failure':  props<{ error: string }>(),
    // P27 Phase 2 — KI-Vorschlag im Wizard
    'Load Ai Autonomy':          emptyProps(),
    'Load Ai Autonomy Success':  props<{ autonomy: AiAutonomyDto }>(),
    'Load Ai Autonomy Failure':  props<{ error: string }>(),
    'Request Import Suggestion':         props<{ request: ImportSuggestionRequest }>(),
    'Request Import Suggestion Success': props<{ jobId: string }>(),
    'Request Import Suggestion Failure': props<{ error: string }>(),
    // Ergebnis des Import-Jobs, aus dem Job-Stream herauskorreliert
    'Import Suggestion Ready':  props<{ result: KnowledgeImportResult }>(),
    'Import Suggestion Failed': props<{ error: string }>(),
    'Reset Import Suggestion':  emptyProps(),
    // P27 Phase 4 — Interview-Mode für private Personen
    'Request Interview':         props<{ request: InterviewSynthesizeRequest }>(),
    'Request Interview Success': props<{ jobId: string }>(),
    'Request Interview Failure': props<{ error: string }>(),
    // Ergebnis des Interview-Jobs, aus dem Job-Stream herauskorreliert
    'Interview Ready':  props<{ result: KnowledgeInterviewResult }>(),
    'Interview Failed': props<{ error: string }>(),
    'Reset Interview':  emptyProps(),
  },
});
